# Generated by Django 4.1.7 on 2023-03-29 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"verbose_name": "автомобиль", "verbose_name_plural": "автомобили"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "категория", "verbose_name_plural": "категории"},
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "город", "verbose_name_plural": "города"},
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "курс", "verbose_name_plural": "курсы"},
        ),
        migrations.AlterModelOptions(
            name="discipline",
            options={"verbose_name": "дисциплина", "verbose_name_plural": "дисциплины"},
        ),
        migrations.AlterModelOptions(
            name="driving",
            options={"verbose_name": "вождение", "verbose_name_plural": "вождения"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "должность", "verbose_name_plural": "должности"},
        ),
        migrations.AlterModelOptions(
            name="region",
            options={"verbose_name": "регион", "verbose_name_plural": "регионы"},
        ),
        migrations.AlterModelOptions(
            name="schedule",
            options={"verbose_name": "расписание", "verbose_name_plural": "расписания"},
        ),
        migrations.AlterModelOptions(
            name="street",
            options={"verbose_name": "улица", "verbose_name_plural": "улицы"},
        ),
        migrations.AlterModelOptions(
            name="training",
            options={"verbose_name": "обучение", "verbose_name_plural": "обучения"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
