# Generated by Django 4.1.7 on 2023-03-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="exam",
            field=models.BooleanField(
                default=False,
                help_text="0 - Не сдано, 1 - Сдано",
                verbose_name="Практическое занятие",
            ),
        ),
    ]
